"""Agrega

Revision ID: 11adb820fc70
Revises: f3dd5ae9f628
Create Date: 2026-03-05 13:36:15.631715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11adb820fc70'
down_revision = 'f3dd5ae9f628'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viajes', schema=None) as batch_op:
        batch_op.drop_column('fecha_carga')
        batch_op.drop_column('fecha_viaje')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viajes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_viaje', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('fecha_carga', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
