"""Agrega campos de auditoria a Viaje

Revision ID: 2d1bec256b3f
Revises: e5e9db64e474
Create Date: 2026-03-02 18:07:53.100684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d1bec256b3f'
down_revision = 'e5e9db64e474'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viajes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ultimo_editado_por', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('fecha_ultima_edicion', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viajes', schema=None) as batch_op:
        batch_op.drop_column('fecha_ultima_edicion')
        batch_op.drop_column('ultimo_editado_por')

    # ### end Alembic commands ###
