"""Agregar campo fecha_arribo_descarga a Viaje

Revision ID: 61b64d011986
Revises: dbf59e401a1e
Create Date: 2026-02-24 18:12:15.517116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61b64d011986'
down_revision = 'dbf59e401a1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viajes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_arribo_descarga', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viajes', schema=None) as batch_op:
        batch_op.drop_column('fecha_arribo_descarga')

    # ### end Alembic commands ###
