"""Add cliente and fecha_arribo_descarga and fecha_retorno_descarga columns to Viaje

Revision ID: c751bb3bf286
Revises: 61b64d011986
Create Date: 2026-02-25 13:15:04.584921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c751bb3bf286'
down_revision = '61b64d011986'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viajes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_retorno_descarga', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viajes', schema=None) as batch_op:
        batch_op.drop_column('fecha_retorno_descarga')

    # ### end Alembic commands ###
