"""Add cliente and fecha_arribo_descarga and fecha_retorno_descarga and fecha_baja columns to Viaje

Revision ID: d851fd7d6dd6
Revises: c751bb3bf286
Create Date: 2026-02-25 16:29:05.381613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd851fd7d6dd6'
down_revision = 'c751bb3bf286'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viajes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_baja', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viajes', schema=None) as batch_op:
        batch_op.drop_column('fecha_baja')

    # ### end Alembic commands ###
