"""Initial coordinador

Revision ID: e5e9db64e474
Revises: d851fd7d6dd6
Create Date: 2026-02-28 09:46:30.265953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5e9db64e474'
down_revision = 'd851fd7d6dd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viajes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coordinador', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viajes', schema=None) as batch_op:
        batch_op.drop_column('coordinador')

    # ### end Alembic commands ###
