"""Agrega fecha_viaje y fecha_carga nullable

Revision ID: f3dd5ae9f628
Revises: 2d1bec256b3f
Create Date: 2026-03-03 16:31:23.129475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3dd5ae9f628'
down_revision = '2d1bec256b3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viajes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_viaje', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('fecha_carga', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viajes', schema=None) as batch_op:
        batch_op.drop_column('fecha_carga')
        batch_op.drop_column('fecha_viaje')

    # ### end Alembic commands ###
